# This ServiceAccount will be used by our example application.
# It adheres to the principle of least privilege by not having any permissions by default.
# Permissions will be granted through a RoleBinding.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-pod-reader-sa # Name of the ServiceAccount
  namespace: secure-app-ns # Namespace where the SA will reside (created by commands.sh)