package com.genai.incident.manager.model;

import java.time.Instant; // Using Instant for timestamp consistency

/**
 * Represents a detailed report generated by the GenAI service,
 * indicating whether an incident was detected and providing its details.
 */
public class IncidentReport {
    private String id;              // Unique identifier for the incident report
    private Instant timestamp;      // When the incident was detected/reported
    private boolean isIncident;     // True if an incident was detected, false otherwise
    private String type;            // Type of incident (e.g., "Memory Leak", "Database Timeout", "Application Error")
    private String description;     // A brief, high-level description of the incident
    private String explanation;     // Detailed explanation of the root cause or contributing factors
    private String resolutionSteps; // Suggested steps to resolve the incident

    // Default constructor for JSON serialization/deserialization
    public IncidentReport() {
    }

    public IncidentReport(String id, Instant timestamp, boolean isIncident, String type, String description, String explanation, String resolutionSteps) {
        this.id = id;
        this.timestamp = timestamp;
        this.isIncident = isIncident;
        this.type = type;
        this.description = description;
        this.explanation = explanation;
        this.resolutionSteps = resolutionSteps;
    }

    // --- Getters and Setters ---
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Instant getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Instant timestamp) {
        this.timestamp = timestamp;
    }

    public boolean getIsIncident() { // Using getIsIncident for boolean property as per Jackson conventions
        return isIncident;
    }

    public void setIsIncident(boolean incident) {
        isIncident = incident;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getExplanation() {
        return explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }

    public String getResolutionSteps() {
        return resolutionSteps;
    }

    public void setResolutionSteps(String resolutionSteps) {
        this.resolutionSteps = resolutionSteps;
    }

    @Override
    public String toString() {
        return "IncidentReport{" +
               "id='" + id + '\'' +
               ", timestamp=" + timestamp +
               ", isIncident=" + isIncident +
               ", type='" + type + '\'' +
               ", description='" + description + '\'' +
               ", explanation='" + explanation + '\'' +
               ", resolutionSteps='" + resolutionSteps + '\'' +
               '}';
    }
}